import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from './Navbar'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className={poppins.className} >
        <ThemeProvider attribute='class' defaultTheme='system'>

        <Navbar />
        <main className='m-10'>
        {children}
        </main>

        </ThemeProvider>
        </body>
    </html>
  )
}
